//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrahent()
        {
            this.Dostawa = new HashSet<Dostawa>();
            this.Faktura = new HashSet<Faktura>();
            this.ZamowienieHurtowe = new HashSet<ZamowienieHurtowe>();
        }
    
        public int IdKontrahenta { get; set; }
        public string Kod { get; set; }
        public string NIP { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> IdRodzaju { get; set; }
        public Nullable<int> IdStatusu { get; set; }
        public Nullable<int> IdAdresu { get; set; }
    
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostawa> Dostawa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Faktura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZamowienieHurtowe> ZamowienieHurtowe { get; set; }
        public virtual Rodzaj Rodzaj { get; set; }
        public virtual Status Status { get; set; }
    }
}
