//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklamacja
    {
        public int IdReklamacji { get; set; }
        public Nullable<int> IdFaktury { get; set; }
        public System.DateTime DataReklamacji { get; set; }
        public string Status { get; set; }
        public string OpisReklamacji { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public string Decyzja { get; set; }
    
        public virtual Faktura Faktura { get; set; }
        public virtual Pracownik Pracownik { get; set; }
    }
}
