//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanMagazynowy
    {
        public int IdStanu { get; set; }
        public Nullable<int> IdTowaru { get; set; }
        public Nullable<int> IdMagazynu { get; set; }
        public int Ilosc { get; set; }
        public Nullable<int> MinimalnyPoziom { get; set; }
        public Nullable<int> MaxymalnyPoziom { get; set; }
    
        public virtual Magazyn Magazyn { get; set; }
        public virtual Towar Towar { get; set; }
    }
}
